# Generated by Django 6.1 on 2026-09-26 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: UPS 1', max_length=100, verbose_name='Nombre del equipo')),
                ('location', models.CharField(help_text='Ej: Zona reservorios - mina raquira', max_length=150, verbose_name='Ubicación')),
                ('host', models.CharField(help_text='Ej: 000.000.0.0', max_length=15, verbose_name='IP del equipo')),
                ('port', models.CharField(default='7660', max_length=5, verbose_name='Puerto TCP')),
                ('is_active', models.BooleanField(default=True, help_text='Marcar actividad', verbose_name='Activo')),
                ('status', models.CharField(choices=[('online', 'En línea'), ('battery', 'Modo batería'), ('offline', 'Desconectado')], default='offline', max_length=25, verbose_name='Estado actual')),
                ('battery_nominal', models.FloatField(default=12.0, help_text='Voltaje nominal de baterias', verbose_name='Voltaje nominal (V)')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Fecha y hora de la última lectura', null=True, verbose_name='Última lectura')),
                ('battery_voltage', models.FloatField(default=12.0, help_text='Voltaje actual del banco de baterias', verbose_name='Voltaje actual (V)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro', verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Dispositivo UPS',
                'verbose_name_plural': 'Dispositivos UPS',
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name=' DD/MM/YYYY HH:MM')),
                ('vin', models.FloatField(help_text='Voltaje de entrada del UPS', verbose_name='Voltaje entrada (V)')),
                ('vin_fault', models.FloatField(default=0.0, help_text='1 = Falla, 0 = Sin falla', verbose_name='Indicador de falla de entrada')),
                ('vout', models.FloatField(verbose_name='Voltaje de salida (V)')),
                ('load_pct', models.FloatField(verbose_name='Carga (%)')),
                ('frequency', models.FloatField(verbose_name='Frecuencia (Hz)')),
                ('battery_voltage', models.FloatField(verbose_name='Voltaje batería (V)')),
                ('temperature', models.FloatField(default=0.0, verbose_name='Temperatura (°C)')),
                ('status_q1', models.CharField(default='00000000', max_length=8, verbose_name='Estado Q1')),
                ('mode', models.CharField(choices=[('grid', 'Red eléctrica'), ('battery', 'Batería')], default='grid', max_length=25, verbose_name='Modo de operación')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.upsdevice')),
            ],
            options={
                'verbose_name': 'Lectura de telemetría',
                'verbose_name_plural': 'Historial de telemetría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PowerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('battery_mode', 'Corte de luz'), ('grid_restored', 'Red eléctrica restaurada'), ('esp_disconnect', 'Pérdida de comunicacion con ESP32'), ('esp_reconnect', 'Reconexión con ESP32'), ('battery_low', 'Batería baja'), ('overload', 'Sobrecarga')], max_length=50, verbose_name='Tipo de evento')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico'), ('emergency', 'Emergencia')], default='info', max_length=20, verbose_name='Severidad')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin / Restauración')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('detail', models.TextField(verbose_name='Detalle del evento')),
                ('notified', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoreo.upsdevice', verbose_name='UPS')),
            ],
            options={
                'verbose_name': 'Evento eléctrico',
                'verbose_name_plural': 'Eventos de energía',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=150, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram Chat ID')),
                ('notify_on_battery', models.BooleanField(default=True, verbose_name='Alertar en corte de luz')),
                ('notify_on_restore', models.BooleanField(default=True, verbose_name='Alertar en restauración de red')),
                ('notify_on_offline', models.BooleanField(default=True, verbose_name='Alerta de desconexión de ESP32')),
                ('voltage_min_alert', models.FloatField(default=100.0, verbose_name='Voltaje Mínimo Alerta (V)')),
                ('voltage_max_alert', models.FloatField(default=135.0, verbose_name='Voltaje Máximo Alerta (V)')),
                ('load_max_alert', models.FloatField(default=85.0, verbose_name='Carga Máxima Alerta (%)')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to='monitoreo.upsdevice', verbose_name='UPS (Vacío = Configuración Global)')),
            ],
            options={
                'verbose_name': 'Configuración de Alertas',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
    ]
